I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 35, in script
    아라 "어쩔티비"
Exception: Sayer '아라' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 35, in script
    아라 "어쩔티비"
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '아라' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ITShow 1.0
Mon Apr 29 00:31:39 2024
